# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to=b'/static/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to=b'/static/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentblock',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_projects.Project'),
        ),
    ]
