# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=[b'C:\\Users\\John\\Documents\\GitHub\\johnwasson.io\\john_wasson/static']),
        ),
    ]
