# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0002_auto_20160328_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(upload_to='john_wasson/static'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='john_wasson/static'),
        ),
    ]
