# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0003_auto_20160328_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='websites', max_length=100),
        ),
    ]
